import AppKit
import Foundation

/// Keeps the Mac's pasteboard and the phone's clipboard holding the same text.
///
/// Both ends run the same rule, which is what stops the obvious disaster. Copy on the Mac, and
/// the phone is told; the phone puts it on its own clipboard, which wakes the phone's clipboard
/// listener, which would tell the Mac, which would set its pasteboard, which would wake this
/// watcher — a loop that never runs out of things to say. So each side remembers the text the
/// two of them last agreed on and refuses to send or apply that exact text again. The loop dies
/// on its first lap.
///
/// The `mirror` also settles the rarer case where both ends are copied to inside the same
/// second: the two clips cross, each end applies the other's, both find their own next reading
/// already equal to the mirror, and it stops there. The two clipboards end up swapped rather
/// than merged, which is untidy and finite — the alternative is an argument neither side can
/// win.
final class PasteboardMirror: @unchecked Sendable {
    /// How often the pasteboard is looked at.
    ///
    /// There is no notification for "the pasteboard changed" on macOS; polling `changeCount`
    /// is the whole of the public API. A second is under the time it takes to move a hand from
    /// one keyboard to another, and reading one integer at 1 Hz does not register on a power
    /// graph.
    static let interval: TimeInterval = 1

    /// Markers that mean "do not record this", by the convention at nspasteboard.org.
    ///
    /// This is the line between a shared clipboard and a password exfiltration tool. A manager
    /// that copies a credential stamps the pasteboard with one of these, and everything that
    /// reads the pasteboard for later use is expected to leave it alone. We do not merely skip
    /// sending it — the mirror is not advanced either, so the next ordinary copy still counts
    /// as news.
    static let concealed: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        // Not part of that convention, and the single most likely source of a password on
        // this particular pasteboard.
        "com.agilebits.onepassword",
    ]

    private let link: any LinkSink
    private let log: Logger
    private let board: NSPasteboard

    /// Every field below is touched only on this queue.
    private let queue = DispatchQueue(label: "cmbridge.clipboard")
    private var timer: DispatchSourceTimer?
    private var lastChangeCount: Int
    private var mirror: String?

    init(link: any LinkSink, log: Logger, board: NSPasteboard = .general) {
        self.link = link
        self.log = log
        self.board = board
        // Whatever is already on the pasteboard when the bridge starts is not news. Starting
        // from zero would push the contents of your clipboard at the first phone to connect,
        // which is a surprising thing for a program to do at login.
        self.lastChangeCount = board.changeCount
    }

    // MARK: - Lifecycle

    func start() {
        reportAccess()
        queue.async { [weak self] in
            guard let self, self.timer == nil else { return }
            let timer = DispatchSource.makeTimerSource(queue: self.queue)
            timer.schedule(deadline: .now() + Self.interval, repeating: Self.interval)
            timer.setEventHandler { [weak self] in self?.poll() }
            timer.resume()
            self.timer = timer
        }
        log.info("clipboard mirroring on — \(Clip.textLimit) bytes of text, both directions")
    }

    func stop() {
        queue.async { [weak self] in
            self?.timer?.cancel()
            self?.timer = nil
        }
    }

    // MARK: - Mac to phone

    /// Internal rather than private so a test can drive a tick without waiting a second for
    /// one. Called on `queue` in production, and from the test thread with no timer running.
    func poll() {
        let count = board.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        // Checked before anything is read. Asking what kinds of data are present is not the
        // same as reading them, and a concealed clip should not be read at all.
        let types = (board.types ?? []).map(\.rawValue)
        if let marker = types.first(where: Self.concealed.contains) {
            log.info("clipboard: skipping a clip marked \(marker)")
            return
        }
        guard let text = board.string(forType: .string), !text.isEmpty else { return }
        guard text != mirror else { return }

        // A clip copied while the phone is away is lost rather than queued: a clipboard is a
        // live thing, and the last thing you copied an hour ago is not what you want appearing
        // under your thumb when the link comes back.
        //
        // The mirror does not advance for it either. The mirror means "what the other end is
        // known to have", and nothing was sent — advancing it here would make copying that
        // same text again once the phone is back look like something already agreed on, and it
        // would never cross.
        guard link.isLinked else { return }
        send(text)
    }

    private func send(_ text: String) {
        let clip = Clip.of(text, at: Int(Date().timeIntervalSince1970))

        // The mirror is what the *phone* will hold, which is the clamped text — not what is on
        // this pasteboard. Setting it to the full text is a silent way to lose data: anything
        // over the limit arrives truncated, and the moment the phone sends its clipboard back
        // that shorter string compares unequal to the original and overwrites it. Measured
        // exactly once, on a 4909-byte clip that came home 4095 bytes long.
        mirror = clip.text ?? text

        // Never the text itself: this log goes to a file that lives in ~/Library/Logs.
        let sent = clip.text?.utf8.count ?? 0
        if sent < text.utf8.count {
            log.info("clipboard: sending \(sent) of \(text.utf8.count) bytes to the phone")
        } else {
            log.info("clipboard: sending \(sent) bytes to the phone")
        }
        guard let payload = try? LineCodec.payload(clip) else { return }
        link.send(payload)
    }

    // MARK: - Phone to Mac

    /// Puts a clip from the phone on this Mac's pasteboard.
    func receive(_ clip: Clip) {
        guard let text = clip.text, !text.isEmpty else {
            log.error("clipboard: a clip from the phone did not decode")
            return
        }
        queue.async { [weak self] in
            guard let self, text != self.mirror else { return }
            self.mirror = text
            self.board.clearContents()
            self.board.setString(text, forType: .string)
            // Taken after the write, not before: both calls above move the counter, and a
            // stale reading here would make the next poll treat our own paste as a local copy
            // and send it straight back.
            self.lastChangeCount = self.board.changeCount
            self.log.info("clipboard: \(text.utf8.count) bytes from the phone")
        }
    }

    // MARK: - Test seams

    /// Waits for whatever `receive` scheduled. The queue is serial, so an empty block behind
    /// the work is enough.
    func settle() {
        queue.sync {}
    }

    // MARK: - Access

    /// Says once, at startup, whether macOS will actually let us read the pasteboard.
    ///
    /// From macOS 15.4 a programmatic read that is not a person pressing paste raises a system
    /// alert, and the standing answer lives in System Settings. A background agent has no way
    /// to be "a person pressing paste", so without the grant this feature is a dialog every
    /// time you copy something — which is worse than not having it. Better to say so at start
    /// than to let it be discovered.
    private func reportAccess() {
        guard #available(macOS 15.4, *) else { return }
        switch board.accessBehavior {
        case .alwaysAllow:
            return
        case .alwaysDeny:
            log.error("""
            clipboard: macOS is denying pasteboard reads, so nothing will be sent to the phone \
            — System Settings › Privacy & Security › Paste from Other Apps › cmbridge › Allow, \
            or run with --no-clipboard to stop asking
            """)
        default:
            log.info("""
            clipboard: macOS will ask before the first read — set it to Allow in System \
            Settings › Privacy & Security › Paste from Other Apps, or the question comes back
            """)
        }
    }
}
